import "server-only";
import { GoogleGenAI } from "@google/genai";
import { db } from "@/lib/db";
import { getSetting } from "@/lib/settings";
import { loadCredential } from "@/lib/providers/credentials";
import { saveBufferToPool } from "@/lib/storage";
import { getMaxUploadBytes } from "@/lib/settings";
import { loadImageByName } from "@/lib/file-tools";
import { isRetryableError } from "@/lib/providers/errors";
import { appLog } from "@/lib/applog";
import type { Credential, ImagePart, ToolDef } from "@/lib/providers/types";
import type { ToolCtx, ToolOutput } from "./types";

/**
 * Image generation / edit / blend — Gemini ONLY (the owner's call: no
 * fallback backend, no cascade; failures are honest tool errors). Outputs
 * land in the conversation pool as kind=generated files (worker ingests →
 * manifest/chips), and ride back to the model as a vision part so it can
 * check its own work. Per-user rolling 7-day quotas per tier — counted
 * straight off usage_records (no extra table).
 */

const FLASH_MODEL = process.env.GEMINI_IMAGE_FLASH_MODEL ?? "gemini-3.1-flash-image";
const PRO_MODEL = process.env.GEMINI_IMAGE_PRO_MODEL ?? "gemini-3-pro-image";
const TIMEOUT_MS = 180_000;
/** Retry transient Google failures (5xx / overloaded / rate-limit / network),
 *  which are common on the preview image models — a single blip shouldn't fail
 *  the whole request (this was the symptom behind "temporary issue"). */
const MAX_ATTEMPTS = 3;

/** Transient = worth retrying: numeric-5xx/429 (isRetryableError) OR a message
 *  the SDK surfaces without a numeric status (UNAVAILABLE / overloaded / …). */
function isTransientImageError(e: unknown): boolean {
  if (isRetryableError(e)) return true;
  const msg = (e instanceof Error ? e.message : String(e)).toLowerCase();
  return /(overload|unavailable|deadline|timeout|try again|rate.?limit|resource.?exhausted|internal error|temporarily|\b50[0-9]\b|\b429\b)/.test(msg);
}

/** Flat USD cost per image (1K/2K bill the same tier on Gemini). */
const IMAGE_COST: Record<string, number> = {
  [FLASH_MODEL]: Number(process.env.GEMINI_FLASH_IMAGE_COST ?? 0.067),
  [PRO_MODEL]: Number(process.env.GEMINI_PRO_IMAGE_COST ?? 0.134),
};

const ASPECT_RATIOS = new Set([
  "1:1", "16:9", "9:16", "4:3", "3:4", "3:2", "2:3", "4:5", "5:4", "21:9",
]);

export interface ImageToolsConfig {
  /** Pin a specific google credential; default = first google org key. */
  credentialId?: string;
  flashWeeklyLimit?: number;
  proWeeklyLimit?: number;
}

async function getImageConfig(): Promise<Required<Omit<ImageToolsConfig, "credentialId">> & ImageToolsConfig> {
  const cfg = (await getSetting<ImageToolsConfig>("image_tools_config")) ?? {};
  return {
    ...cfg,
    flashWeeklyLimit: cfg.flashWeeklyLimit ?? Number(process.env.GEMINI_FLASH_WEEKLY_LIMIT ?? 20),
    proWeeklyLimit: cfg.proWeeklyLimit ?? Number(process.env.GEMINI_PRO_WEEKLY_LIMIT ?? 5),
  };
}

async function getGoogleCredential(pinnedId?: string): Promise<Credential | null> {
  if (pinnedId) return loadCredential(pinnedId);
  const row = await db.providerCredential.findFirst({
    where: { provider: "google" },
    orderBy: { createdAt: "asc" },
  });
  return row ? loadCredential(row.id) : null;
}

/** Images generated by this user on this model in the rolling window. */
/** Estimated generation time (ms) from the last few real generations of this
 *  operation — powers the placeholder's live countdown. Reads genMs from
 *  recent replies' `meta.images` (app-owned; the ingestion worker rewrites the
 *  file meta, so that's not reliable). Falls back to a sane default before any
 *  history exists. */
const estimateCache = new Map<string, { at: number; ms: number }>();
const ESTIMATE_TTL_MS = 10 * 60_000;

export async function estimateImageMs(operation?: string): Promise<number> {
  const DEFAULT_MS = 14_000;
  // Cached: this runs INSIDE the turn, before the image placeholder is emitted,
  // and it only feeds a countdown. Ten minutes of staleness costs nothing and
  // keeps a database read off the hot path.
  const key = operation ?? "*";
  const hit = estimateCache.get(key);
  if (hit && Date.now() - hit.at < ESTIMATE_TTL_MS) return hit.ms;
  const rows = await db.message.findMany({
    where: { role: "assistant" },
    orderBy: { createdAt: "desc" },
    take: 40,
    select: { meta: true },
  });
  const times: number[] = [];
  for (const r of rows) {
    const imgs = (r.meta as { images?: { genMs?: number; operation?: string }[] } | null)?.images;
    if (!imgs) continue;
    for (const im of imgs) {
      if (typeof im.genMs === "number" && im.genMs > 0 && (!operation || im.operation === operation)) {
        times.push(im.genMs);
      }
    }
    if (times.length >= 8) break;
  }
  if (times.length === 0) {
    estimateCache.set(key, { at: Date.now(), ms: DEFAULT_MS });
    return DEFAULT_MS;
  }
  const recent = times.slice(0, 8);
  const ms = Math.round(recent.reduce((a, b) => a + b, 0) / recent.length);
  estimateCache.set(key, { at: Date.now(), ms });
  return ms;
}

async function usedThisWeek(userId: string, model: string): Promise<number> {
  const weekAgo = new Date(Date.now() - 7 * 864e5);
  return db.usageRecord.count({
    where: { userId, role: "image", model, createdAt: { gte: weekAgo } },
  });
}

// ---------------------------------------------------------------------------
// Tool definitions
// ---------------------------------------------------------------------------

const COMMON_PROPS = {
  aspect_ratio: {
    type: "string",
    description: "One of 1:1, 16:9, 9:16, 4:3, 3:4, 3:2, 2:3, 4:5, 5:4, 21:9 (default 1:1).",
  },
  quality: {
    type: "string",
    description: '"standard" (default) or "max" (higher fidelity, stricter weekly quota).',
  },
};

export const IMAGE_GENERATION_DEF: ToolDef = {
  name: "image_generation",
  description:
    "Generate an image from a text prompt — a PHOTO, ILLUSTRATION or CONCEPT picture. NOT for adverts, social posts, banners, posters, flyers, slides, mockups or anything whose text and layout must be right: those are BUILT (HTML/CSS → exact-size PNG) via the design-graphics skill — load it first, it asks the user which they want. The image is saved to this conversation's files (the user can download it) and attached for you to review.",
  parameters: {
    type: "object",
    properties: {
      prompt: { type: "string", description: "Detailed description of the image to create." },
      ...COMMON_PROPS,
    },
    required: ["prompt"],
  },
};

export const IMAGE_EDIT_DEF: ToolDef = {
  name: "image_edit",
  description:
    "Edit an existing image from this conversation's files using a text instruction (e.g. 'remove the background', 'make it night time').",
  parameters: {
    type: "object",
    properties: {
      prompt: { type: "string", description: "The edit instruction." },
      image: { type: "string", description: "Exact filename of the source image." },
      ...COMMON_PROPS,
    },
    required: ["prompt", "image"],
  },
};

export const IMAGE_BLEND_DEF: ToolDef = {
  name: "image_blend",
  description:
    "Combine 2-4 images from this conversation's files into one new image, guided by a text prompt.",
  parameters: {
    type: "object",
    properties: {
      prompt: { type: "string", description: "How to combine them." },
      images: {
        type: "array",
        items: { type: "string" },
        description: "2-4 exact filenames of the source images.",
      },
      ...COMMON_PROPS,
    },
    required: ["prompt", "images"],
  },
};

// ---------------------------------------------------------------------------
// Core
// ---------------------------------------------------------------------------

interface GenArgs {
  prompt: string;
  aspectRatio: string;
  quality: "standard" | "max";
  sources: ImagePart[];
  operation: "generate" | "edit" | "blend";
}

async function runImageModel(ctx: ToolCtx, args: GenArgs): Promise<string | ToolOutput> {
  const cfg = await getImageConfig();
  const cred = await getGoogleCredential(cfg.credentialId);
  if (!cred) {
    return "Error: image generation isn't configured (no Google credential on this server — an admin can add one).";
  }

  const model = args.quality === "max" ? PRO_MODEL : FLASH_MODEL;
  const limit = args.quality === "max" ? cfg.proWeeklyLimit : cfg.flashWeeklyLimit;
  const used = await usedThisWeek(ctx.userId, model);
  if (used >= limit) {
    // Each tier has its own counter, so a helpful model could silently hop
    // tiers and the user would never learn a quota exists (found in owner
    // testing) — the refusal must demand transparency, not suggest a bypass.
    // Guidance sits behind the marker: the image placeholder shows only the
    // user-facing sentence.
    const other = args.quality === "max" ? "standard" : "max";
    return (
      `Error: weekly image quota reached — ${used}/${limit} "${args.quality}"-quality images ` +
      `in the last 7 days (the rolling window frees up as older generations age out). ` +
      `[To the assistant: tell the user plainly that their weekly ${args.quality}-quality image ` +
      `allowance is used up. Do NOT silently retry at "${other}" quality — it has its own separate ` +
      `quota${args.quality === "standard" ? " and costs more" : ""}; you may OFFER it as an explicit choice.]`
    );
  }

  const ai = new GoogleGenAI({ apiKey: cred.secret });
  const parts: Record<string, unknown>[] = [
    ...args.sources.map((s) => ({
      inlineData: { mimeType: s.mimeType, data: s.dataBase64 },
    })),
    { text: args.prompt },
  ];

  // Retry loop: retry on transient THROWS (5xx/overload/rate-limit) AND on an
  // EMPTY response (the API returns no image part but no error — also usually
  // transient/rate-limit). A response with explanatory TEXT (a refusal) is a
  // content decision, not transient → surface it, don't retry. Only break with
  // a valid image in hand.
  let img: { inlineData: { mimeType?: string; data?: string } } | undefined;
  let usageMetadata: Awaited<ReturnType<typeof ai.models.generateContent>>["usageMetadata"];
  let lastErr: unknown;
  const genT0 = Date.now(); // time the actual generation, for the ETA estimate
  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    try {
      const res = await ai.models.generateContent({
        model,
        contents: [{ role: "user", parts }],
        config: {
          responseModalities: ["IMAGE"],
          imageConfig: {
            aspectRatio: args.aspectRatio,
            imageSize: args.quality === "max" ? "2K" : "1K",
          },
          // Fresh timeout per attempt (a used signal would abort instantly).
          abortSignal: AbortSignal.timeout(TIMEOUT_MS),
        },
      });
      const outParts = res.candidates?.[0]?.content?.parts ?? [];
      const found = outParts.find(
        (p): p is { inlineData: { mimeType?: string; data?: string } } =>
          !!(p as { inlineData?: unknown }).inlineData,
      );
      if (found?.inlineData?.data) {
        img = found;
        usageMetadata = res.usageMetadata; // captured for billing after the loop
        break;
      }
      // No image. If the model explained itself, it's a refusal — don't retry.
      const text = outParts.map((p) => (p as { text?: string }).text ?? "").join(" ").trim();
      if (text) {
        await appLog("warn", "image", `Image ${args.operation}: model returned text, no image`, {
          userId: ctx.userId, details: { model, text: text.slice(0, 300) },
        });
        return `Error: the model returned no image (it said: ${text.slice(0, 200)}).`;
      }
      // Empty response → transient; retry.
      lastErr = new Error("empty response (no image part)");
      await appLog(attempt < MAX_ATTEMPTS ? "warn" : "error", "image", `Image ${args.operation}: empty response (attempt ${attempt}/${MAX_ATTEMPTS})`, {
        userId: ctx.userId, details: { model, attempt },
      });
      if (attempt < MAX_ATTEMPTS) await new Promise((r) => setTimeout(r, 800 * attempt));
    } catch (e) {
      lastErr = e;
      const retryable = isTransientImageError(e) && attempt < MAX_ATTEMPTS;
      await appLog(retryable ? "warn" : "error", "image", `Image ${args.operation} failed (attempt ${attempt}/${MAX_ATTEMPTS})`, {
        userId: ctx.userId,
        details: { model, attempt, retryable, error: (e instanceof Error ? e.message : String(e)).slice(0, 400) },
      });
      if (!retryable) break;
      await new Promise((r) => setTimeout(r, 800 * attempt)); // 0.8s, 1.6s backoff
    }
  }
  if (!img?.inlineData?.data) {
    const m = lastErr instanceof Error ? lastErr.message.slice(0, 300) : String(lastErr);
    // Gemini's image models sometimes 500 INTERNAL on a specific prompt+image
    // combination rather than failing cleanly (seen live: two elaborate blend
    // prompts 500'd 3/3 while a plain one with the SAME sources succeeded
    // seconds later) — so steer the retry toward a simpler prompt, not a
    // verbatim re-run. Guidance behind the marker: users see only the first
    // sentence in the image placeholder.
    return `Error: image ${args.operation} failed after ${MAX_ATTEMPTS} attempt(s): ${m}. This is often a temporary Google-side issue. [To the assistant: elaborate prompts can trigger this repeatedly — retry once with a NOTICEABLY shorter, simpler prompt (same source images are fine).]`;
  }

  const mime = img.inlineData.mimeType ?? "image/png";
  const ext = mime.includes("jpeg") ? "jpg" : mime.includes("webp") ? "webp" : "png";
  const buffer = Buffer.from(img.inlineData.data, "base64");
  const stored = await saveBufferToPool(
    ctx.conversationId,
    `${args.operation}-${new Date().toISOString().slice(0, 19).replace(/[-:T]/g, "")}.${ext}`,
    buffer,
    await getMaxUploadBytes(),
  );
  const row = await db.file.create({
    data: {
      userId: ctx.userId,
      conversationId: ctx.conversationId,
      filename: stored.storedName,
      mimeType: mime,
      detectedMime: mime,
      sizeBytes: BigInt(stored.sizeBytes),
      storagePath: stored.storagePath,
      kind: "generated",
      meta: {
        operation: args.operation,
        model,
        prompt: args.prompt.slice(0, 500),
        aspectRatio: args.aspectRatio,
        genMs: Date.now() - genT0,
      },
    },
  });

  // Bill the image: flat per-image cost + whatever tokens the call reported.
  const um = usageMetadata;
  await db.usageRecord.create({
    data: {
      userId: ctx.userId,
      role: "image",
      provider: "google",
      model,
      inputTokens: um?.promptTokenCount ?? 0,
      outputTokens: um?.candidatesTokenCount ?? 0,
      cacheReadTokens: 0,
      cacheWriteTokens: 0,
      costEstimate: IMAGE_COST[model] ?? 0.067,
    },
  });

  return {
    text:
      `Created "${stored.storedName}" (${mime}, ${args.aspectRatio}, ${args.quality}) — saved to this ` +
      `conversation's files and attached for your review. Weekly quota: ${used + 1}/${limit}.`,
    images: [{ mimeType: mime, dataBase64: img.inlineData.data }],
    artifact: {
      fileId: row.id,
      mimeType: mime,
      aspectRatio: args.aspectRatio,
      prompt: args.prompt,
      operation: args.operation,
      genMs: Date.now() - genT0,
    },
  };
}

// ---------------------------------------------------------------------------
// Executors
// ---------------------------------------------------------------------------

function commonArgs(args: Record<string, unknown>) {
  const aspect = String(args.aspect_ratio ?? "1:1");
  return {
    prompt: String(args.prompt ?? "").trim(),
    aspectRatio: ASPECT_RATIOS.has(aspect) ? aspect : "1:1",
    quality: (args.quality === "max" ? "max" : "standard") as "standard" | "max",
  };
}

export async function executeImageGeneration(
  args: Record<string, unknown>,
  ctx: ToolCtx,
): Promise<string | ToolOutput> {
  const base = commonArgs(args);
  if (!base.prompt) return "Error: prompt is required.";
  return runImageModel(ctx, { ...base, sources: [], operation: "generate" });
}

export async function executeImageEdit(
  args: Record<string, unknown>,
  ctx: ToolCtx,
): Promise<string | ToolOutput> {
  const base = commonArgs(args);
  if (!base.prompt) return "Error: prompt is required.";
  const name = String(args.image ?? "").trim();
  if (!name) return "Error: image (source filename) is required.";
  const src = await loadImageByName(ctx.conversationId, name, base.quality);
  if (typeof src === "string") return src;
  return runImageModel(ctx, { ...base, sources: [src], operation: "edit" });
}

export async function executeImageBlend(
  args: Record<string, unknown>,
  ctx: ToolCtx,
): Promise<string | ToolOutput> {
  const base = commonArgs(args);
  if (!base.prompt) return "Error: prompt is required.";
  const names = Array.isArray(args.images) ? args.images.map(String) : [];
  if (names.length < 2 || names.length > 4) {
    return "Error: provide 2-4 source image filenames.";
  }
  const sources: ImagePart[] = [];
  for (const n of names) {
    const src = await loadImageByName(ctx.conversationId, n.trim(), base.quality);
    if (typeof src === "string") return src;
    sources.push(src);
  }
  return runImageModel(ctx, { ...base, sources, operation: "blend" });
}
